version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres-iot
    environment:
      POSTGRES_USER: iot_user
      POSTGRES_PASSWORD: iot_senha123
      POSTGRES_DB: iot_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
